[tools]
node = "22.22.0"
"npm:@devcontainers/cli" = "latest"
pre-commit = "latest"
python = "3.14.3"
ruby = "4.0.1"
terraform = "1.14.4"
tflint = "latest"
trivy = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
