[window]
padding = { x = 4, y = 2 }
opacity = 0.75
blur = true
startup_mode = "Fullscreen"
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 5

[font]
size = 16.0
offset = { x = 0, y = 4 }
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }


[terminal]
shell = { program = "/bin/zsh", args = [
  "-l",
  "-c",
  "tmux new-session -A -s main",
] }
